# Generated by Django 5.2.6 on 2025-09-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_score', '0002_client_address_client_email_client_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='debt_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Коэффициент долговой нагрузки'),
        ),
        migrations.AddField(
            model_name='client',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ежемесячный доход'),
        ),
        migrations.AddField(
            model_name='client',
            name='num_30_59_days_past_due',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество просрочек (30-59 дней)'),
        ),
        migrations.AddField(
            model_name='client',
            name='num_credit_lines_loans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество кредитных линий/займов'),
        ),
        migrations.AddField(
            model_name='client',
            name='utilization',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент использования кредита'),
        ),
    ]
