# Generated by Django 5.2.6 on 2025-09-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_score', '0004_remove_client_address_remove_client_debt_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='debt_ratio',
            field=models.FloatField(default=0.0, help_text='Ежемесячные платежи по долгам / Ежемесячный доход', verbose_name='Коэффициент долговой нагрузки (DebtRatio)'),
        ),
        migrations.AddField(
            model_name='client',
            name='monthly_income',
            field=models.FloatField(blank=True, default=0.0, help_text='Ежемесячный доход клиента', null=True, verbose_name='Ежемесячный доход (MonthlyIncome)'),
        ),
        migrations.AddField(
            model_name='client',
            name='num_30_59_days_past_due',
            field=models.IntegerField(default=0, help_text='Количество раз, когда клиент был просрочен на 30-59 дней', verbose_name='Количество просрочек (30-59 дней)'),
        ),
        migrations.AddField(
            model_name='client',
            name='num_credit_lines_loans',
            field=models.IntegerField(default=0, help_text='Количество активных кредитных линий и/или займов', verbose_name='Количество кредитных линий/займов (NumCreditLinesLoans)'),
        ),
        migrations.AddField(
            model_name='client',
            name='utilization',
            field=models.FloatField(default=0.0, help_text='Остаток по кредиту / Лимит кредита', verbose_name='Процент использования кредита (Utilization)'),
        ),
    ]
