# Generated by Django 5.2.6 on 2025-09-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_score', '0005_client_debt_ratio_client_monthly_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, help_text='Полный адрес проживания клиента', null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('ACTIVE', 'Активный'), ('VIP', 'VIP-клиент'), ('BLOCKED', 'Заблокирован')], default='NEW', help_text='Текущий статус клиента в банке', max_length=10, verbose_name='Статус клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='credit_score_rating',
            field=models.IntegerField(blank=True, help_text='Общий кредитный рейтинг клиента (например, от 300 до 850)', null=True, verbose_name='Общий кредитный рейтинг'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text='Адрес электронной почты клиента', max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Контактный номер телефона клиента', max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
