# Generated by Django 5.2.6 on 2025-09-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_score', '0006_client_address_client_client_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='credit_score_rating',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='debt_ratio',
            field=models.FloatField(verbose_name='Коэффициент долговой нагрузки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='monthly_income',
            field=models.FloatField(default=0, verbose_name='Ежемесячный доход'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='num_30_59_days_past_due',
            field=models.IntegerField(verbose_name='Количество просрочек (30-59 дней)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='num_credit_lines_loans',
            field=models.IntegerField(verbose_name='Количество кредитных линий/займов'),
        ),
        migrations.AlterField(
            model_name='client',
            name='utilization',
            field=models.FloatField(verbose_name='Процент использования кредита'),
        ),
    ]
